services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements_frozen.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    repo: https://github.com/Pitrified/fullstack-render-app
    branch: main
    autoDeploy: true
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: userdb
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  - type: web
    name: react-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    repo: https://github.com/Pitrified/fullstack-render-app
    branch: main
    autoDeploy: true
    rootDir: frontend
    envVars:
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: VITE_API_BASE_URL
        value: https://fastapi-backend-yf8l.onrender.com

databases:
  - name: userdb
    plan: free
